# AeroSpace config

after-login-command = []
after-startup-command = []
start-at-login = false
accordion-padding = 0
default-root-container-layout = 'tiles' # tiles|accordion
default-root-container-orientation = 'horizontal' # horizontal|vertical|auto
automatically-unhide-macos-hidden-apps = true # Unhide-app

# Normalizations.
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

[key-mapping]
    preset = 'qwerty'

[gaps]
    inner.horizontal = 10
    inner.vertical =   10
    outer.left =       10
    outer.bottom =     10
    outer.top =        10
    outer.right =      10

# Fallback value (if you omit the key): mode.main.binding = {}
[mode.main.binding]

    alt-period = 'fullscreen'
    alt-comma = 'layout floating tiling'

    # Layouts
    # alt-comma = 'layout accordion horizontal vertical'
    alt-backspace = 'layout tiles horizontal vertical'

    # alt-comma = 'workspace-back'

    # Focus
    cmd-h = 'focus left'
    cmd-j = 'focus down'
    cmd-k = 'focus up'
    cmd-l = 'focus right'

    cmd-left = 'focus left'
    cmd-down = 'focus down'
    cmd-up = 'focus up'
    cmd-right = 'focus right'

    # Move
    cmd-shift-h = 'move left'
    cmd-shift-j = 'move down'
    cmd-shift-k = 'move up'
    cmd-shift-l = 'move right'

    cmd-shift-left = 'move left'
    cmd-shift-down = 'move down'
    cmd-shift-up = 'move up'
    cmd-shift-right = 'move right'

    # Resize
    cmd-shift-minus = 'resize smart -50'
    cmd-shift-equal = 'resize smart +50'

    # Workspace
    cmd-1 = 'workspace 1'
    cmd-2 = 'workspace 2'
    cmd-3 = 'workspace 3'
    cmd-4 = 'workspace 4'
    cmd-5 = 'workspace 5'
    cmd-6 = 'workspace 6'
    cmd-7 = 'workspace 7'
    cmd-8 = 'workspace 8'
    cmd-9 = 'workspace 9'

    # Move-node-to-workspace
    cmd-shift-1 = 'move-node-to-workspace 1'
    cmd-shift-2 = 'move-node-to-workspace 2'
    cmd-shift-3 = 'move-node-to-workspace 3'
    cmd-shift-4 = 'move-node-to-workspace 4'
    cmd-shift-5 = 'move-node-to-workspace 5'
    cmd-shift-6 = 'move-node-to-workspace 6'
    cmd-shift-7 = 'move-node-to-workspace 7'
    cmd-shift-8 = 'move-node-to-workspace 8'
    cmd-shift-9 = 'move-node-to-workspace 9'

    # Service Mode
    alt-shift-semicolon = 'mode service'

# 'service' binding mode declaration.
[mode.service.binding]
    esc = ['reload-config', 'mode main']
    r = ['flatten-workspace-tree', 'mode main'] # reset layout
    f = ['layout floating tiling', 'mode main'] # Toggle between floating and tiling layout
    backspace = ['close-all-windows-but-current', 'mode main']

    #s = ['layout sticky tiling', 'mode main'] # sticky is not yet supported
    cmd-shift-h = ['join-with left', 'mode main']
    cmd-shift-j = ['join-with down', 'mode main']
    cmd-shift-k = ['join-with up', 'mode main']
    cmd-shift-l = ['join-with right', 'mode main']
